# This is the CD file I use to deploy my notes site
# Like a normal GH Action you will place this in `.github/workflows` to use

name: Build and Deploy MkDocs Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install MkDocs and dependencies
        run: |
          pip install -r requirements.txt

      - name: Filter and copy published notes
        run: |
          python .scripts/collect_published_files.py

      - name: Preprocess Obsidian features
        run: |
          python .scripts/preprocess_link_ids.py
          python .scripts/preprocess_dataviews.py
          echo "Preprocessed Obsidian features in markdown files."

      - name: Deploy MkDocs to GitHub Pages
        run: |
          mkdocs gh-deploy --force --config-file mkdocs.yml
